hook global WinCreate .* %{addhl number_lines -hlcursor}
hook global WinCreate .* %{addhl show_matching}
hook global WinCreate .* %{addhl column 80 ColorColumn}
hook global InsertChar \t 'exec <backspace><space><space>'
colorscheme custom
set global ui_options ncurses_assistant=none:ncurses_wheel_down_button=5
set global indentwidth 2
set global scrolloff 5,5
set global toolsclient unnamed1
map global user c <a-s>:comment-line<ret>
map global user u <a-s>gh///<space><ret>d
map global user l :pdflatex<ret>
map global user q :autowrap-selection<ret>
map global user "'" i'<esc>a'<esc>
map global user '"' i"<esc>a"<esc>
map global user '$' i$<esc>a$<esc>
map global user [ i[<esc>a]<esc>
map global user { i{<esc>a}<esc>
