# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = ""
"rust" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"chromium" = ""
"file manager" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"nvim" = ""
"gthumb" = ""
"menu" = ""
"calculator" = ""
"transmission" = ""
"videostream" = ""
"mpv" = ""
"music" = ""
"disk usage" = ""
".pdf" = ""
"gnome-terminal-server" = ""
"code-oss" = ""
"zoom" = ""
"gedit" = ""
"nautilus" = ""
"droidcam" = ""
"evolution" = ""
"geary" = ""
"keepassxc" = ""
"seahorse" = ""
"dejadup" = ""
"signal" = ""
"software" = ""
"clocks" = ""
"spotify" = ""

[other]
"fallback_icon" = ""
