version: '2.4'

# From https://github.com/FreshRSS/FreshRSS/tree/edge/Docker/freshrss

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./config:/config
    environment:
      TZ: Europe/Paris
      CRON_MIN: '3,33'
    ports:
      - '${PUBLISHED_PORT:-8080}:80'
  freshrss-db:
    image: postgres:14
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_BASE:-freshrss}
      POSTGRES_USER: ${DB_USER:-freshrss}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-freshrss}
